/*
 * This file was automatically generated by EvoSuite
 * Sun May 29 17:13:00 GMT 2022
 */

package assignments.sheet_7;

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BinTreeTraversal_ESTest extends BinTreeTraversal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BinTreeTraversal.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BinTreeTraversal binTreeTraversal0 = new BinTreeTraversal();
  }
}
